name: Build Unsigned IPA

on:
  workflow_dispatch:  # 手動実行可能にする

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # アーカイブ生成
      - name: Archive with xcodebuild
        uses: mxcl/xcodebuild@v3
        with:
          action: archive
          scheme: "IDA Pro - RHgrive"
          platform: iOS
          configuration: Release

      # ExportOptions.plist を作成（署名なし）
      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>signingCertificate</key>
              <string>-</string>
          </dict>
          </plist>
          EOF

      # IPA エクスポート（未署名）
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "IDA Pro - RHgrive.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath output

      # IPA アップロード
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: output/*.ipa
