name: Build IPA from SwiftPM

on:
  workflow_dispatch:  # 手動実行トリガー

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # CocoaPods や XcodeGen を使わない SwiftPM だけの構成
      - name: Archive with mxcl/xcodebuild
        uses: mxcl/xcodebuild@v3
        with:
          action: archive
          scheme: "IDA Pro - RHgrive"   # ← Package.swift 内 iOSApplication の name
          platform: iOS
          configuration: Release

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "$(pwd)/IDA Pro - RHgrive.xcarchive" \
            -exportOptionsPlist "$(pwd)/ExportOptions.plist" \
            -exportPath "$(pwd)"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: IDA-IPA
          path: "IDA Pro - RHgrive.ipa"
